#!/bin/sh

### This script increases/decreases brightness(using "light" commandline application) and gives a notification(using dunstify)!

# Icon
path="~/.icons/"       # Path to icons
icons=( "b1.png" "b2.png" "b3.png" "b4.png" "b5.png" "b6.png" "b7.png" "b8.png" "b9.png" "b10.png" )       # 10 icons for 10 levels of brightness

# Decrease brightness
if [ "$1" = "down" ]; then
    sudo light -U 5
    BRI_PERC=$(($(light -G | tr -d .)/100))   # Getting the value after decrement
    i=$((BRI_PERC/10))       # Calculating icon index based on brightness level
    icon=${icons[$i]}       # Selecting icon based on calcualted index
    dunstify -u low -r 90210 -i $path$icon "Brightness is at $(printf %i%% $(light -G))"   # Notification with brightness after decrement
fi

# Increase brightness
if [ "$1" = "up" ]; then
    sudo light -A 5
    BRI_PERC=$(($(light -G | tr -d .)/100))   # Getting the value after increment
    i=$((BRI_PERC/10))       # Calculating icon index based on brightness level
    icon=${icons[$i]}       # Selecting icon based on calcualted index
    if [ $BRI_PERC -eq 100 ]; then       # Explicitly selecting icon for 100% because above calculation doesn't work when brightness is 100%
        icon=${icons[9]}
    fi
    dunstify -u low -r 90210 -i $path$icon "Brightness is at $(printf %i%% $(light -G))"       # Notification with brightness after increment
fi

exit 0
