#!/bin/bash

### This script gives a notification(using dunstify) with current volume when headphones are connected and when they are removed!

# Path to icon
icon_hp="~/.icons/headphones.png"

# Flag variable to ensure notification is displayed only once at event start
declare -i flag=1

# Infinite loop to continually check status while laptop is powered on
while :; do

    # Getting hedphone status
    hp=$(pactl list sinks | awk 'NR==52 { print $5 }' | tr -d ')')

    # Notification for headphones plugged in
    if [ $hp = "available" -a $flag = "1" ]; then
        # Volume when headphones plugged in
        cur_vol=$(pactl list sinks | awk '/Volume/ { print $12 }')
        dunstify -u low -r 90209 -i $icon_hp "Headphones Connected!" "Volume is at $(printf %s $cur_vol)"
        flag=0
    fi

    # Notification for headphones unplugged
    if [ $hp = "not" -a $flag = "0" ]; then
        # Volume when headphones plugged out
        cur_vol=$(pactl list sinks | awk '/Volume/ { print $12 }')
        dunstify -u low -r 90209 -i $icon_hp "Headphones Disconnected!" "Volume is at $(printf %s $cur_vol)"
        flag=1
    fi

    sleep 3

done

exit 0
