#!/bin/sh

# Icons
wifi_on="~/.icons/wifi_on.png"
wifi_off="~/.icons/wifi_off.png"

# Flag variable to ensure notification is displayed only once at event start
declare -i flag=0

while :; do

    # Getting wifi status
    wifi="$(nmcli r wifi | awk 'FNR = 2 {print $1}')"

    if [ $wifi = "enabled" -a $flag = "1" ]; then
        dunstify -u low -r 90109 -i $wifi_on " WIFI ON"              # Notification for wifi off
        flag=0
    fi

    if [ $wifi = "disabled" -a $flag = "0" ]; then
        dunstify -u low -r 90109 -i $wifi_off " WIFI OFF"            # Notification for wifi on
        flag=1
    fi

    sleep 3

done

exit 0
