#!/usr/bin/env fish

# Set shell for keyboard daemon (should be bash)
set -x SXHKD_SHELL (which bash)

#
# required daemons
#

# Run Keyboard Daemon
sxhkd &

# Start Polybar
~/.config/polybar/launch.sh

# Set Cursor
xsetroot -cursor_name left_ptr &

#
# Bspwm Configuration
#

# define monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9

# and split ratio
bspc config split_ratio 0.50

# borders and gaps
bspc config border_width 2
bspc config window_gap 3
bspc config top_padding 19

# Colors
bspc config normal_border_color		      "#1d2021"
bspc config active_border_color	          "#8ec07c"
bspc config focused_border_color	      "#8ec07c"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#cc241d"

# Monocle Settings
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

# focus window under cursor
bspc config focus_follows_pointer true

# Window Rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a Emacs state=tiled follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
